### ISSUE TITLE
fallthrough not work at online example

### ISSUE THREAD

**Issue by Phinome** [Go-zh/tour#248]
上下文: https://tour.go-zh.org/flowcontrol/9

```golang
package main

import (
	"fmt"
	"runtime"
)

func main() {
	fmt.Print("Go runs on ")
	switch os := runtime.GOOS; os {
	case "darwin":
		fmt.Println("OS X.")
		fallthrough
	case "linux":
		fmt.Println("Linux.")
		fallthrough
	default:
		// freebsd, openbsd,
		// plan9, windows...
		fmt.Printf("%s.", os)
	}
}

```
The code output in browser is:
```text
Go runs on nacl.
Program exited.
```

but, run in local file, result:

```text
Go runs on OS X.
Linux.
darwin.%
```

why ? it is a chrome bug , or go server bug ?

**Comment by OlingCat** [comment]
不是 bug，nacl 是 chrome 运行的环境。

**Comment by Phinome** [comment]
我的意思是 `fallthrough` 的语义不是直接执行下一条 `case` 语句，并且忽略 `case` 判断直接执行其语句么？那么输出结果就应该是：
```text
   Go runs on nacl.
Linux.
nac.% 
```

**Comment by Phinome** [comment]
我的意思是 `fallthrough` 的语义不是直接执行下一条 `case` 语句，并且忽略 `case` 判断直接执行其语句么？那么输出结果就应该是：
```text
   Go runs on nacl.
Linux.
nac.% 
```

**Comment by OlingCat** [comment]
对呀，因为你的系统是Darwin，所以第一个匹配完就一直下穿了；而浏览器的话前两个都没匹配到，所以只有default的NaCl了啊

Phinome <notifications@github.com>于2017年4月10日周一 00:24写道：

我的意思是 fallthrough 的语义不是直接执行下一条 case 语句，并且忽略 case 判断直接执行其语句么？那么输出结果就应该是：

   Go runs on nacl.
Linux.
nac.%

—
You are receiving this because you commented.


Reply to this email directly, view it on GitHub
<https://github.com/Go-zh/tour/issues/248#issuecomment-292795949>, or mute
the thread

**Comment by Phinome** [comment]
嗯，我理解错了，多谢~
